### ISSUE TITLE
The build breaks for `go get` because of analytics-go

### ISSUE THREAD

**Issue by prasincs** [segmentio/aws-okta#40] opened 2018-04-11 05:44 UTC
When I follow the instructions in README, I'm getting the following

```
[22:28:04] [~/go/src/github.com/segmentio/aws-okta] [master *]
-> % go install
# github.com/segmentio/aws-okta/cmd
cmd/add.go:37:41: cannot convert nil to type analytics.Client
cmd/add.go:38:18: analyticsClient.Enqueue undefined (type analytics.Client has no field or method Enqueue)
cmd/add.go:41:16: undefined: analytics.NewProperties
cmd/exec.go:119:41: cannot convert nil to type analytics.Client
cmd/exec.go:120:18: analyticsClient.Enqueue undefined (type analytics.Client has no field or method Enqueue)
cmd/exec.go:123:16: undefined: analytics.NewProperties
cmd/login.go:71:41: cannot convert nil to type analytics.Client
cmd/login.go:72:18: analyticsClient.Enqueue undefined (type analytics.Client has no field or method Enqueue)
cmd/login.go:75:16: undefined: analytics.NewProperties
cmd/root.go:29:2: cannot use nil as type analytics.Client in assignment
cmd/login.go:75:16: too many errors
```
surely there's no `Enqueue` method in analytics-go's client code.. if I rip out all the analytics, it compiles fine. This looks like an internal interface that works at segment but isn't externally available or library dependency. 

I'm providing the patch as a sample of what I was doing, not as a PR (obviously if people want analytics, they should be able to configure it), but please don't break the open source facing builds.

[out.patch.txt](https://github.com/segmentio/aws-okta/files/1897393/out.patch.txt)

**Comment by dfuentes** [comment] 2018-04-11 05:57
The issue is that we are using the 3.0 version of that library which is not in the master branch.  We use govendor to reference this version.

While the build may fail during `go get`, you can still clone the repo and build with:
```bash
$ go get github.com/kardianos/govendor
$ govendor sync
$ go build
```

It's possible we can check in our vendored libraries to make go get work again.

**Comment by prasincs** [comment] 2018-04-11 06:10
Thanks @dfuentes. Yeah, that might be good idea. I added a suggestion to README in the PR, but avoiding breaking install in first place is ideal

**Comment by dfuentes** [comment] 2018-04-19 21:31
I've checked in the vendored libs now, so `go get` should be working again.  Going to close this issue.

**Closed by dfuentes** 2018-04-19 21:31 UTC
