### ISSUE TITLE
Can't install due to go1.10 compilation errors

### ISSUE THREAD

**Issue by yangmillstheory** [segmentio/aws-okta#25] opened 2018-03-12 16:57 UTC
I haven't used `go` in a while and I'm by no means an expert, but these look like compiler errors from library code.

```
👌 /U/valvarez
(i) go get -v github.com/segmentio/aws-okta
github.com/99designs/keyring/vendor/github.com/keybase/go-keychain
# github.com/99designs/keyring/vendor/github.com/keybase/go-keychain
go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:29: cannot use nil as type _Ctype_CFDataRef in return argument
go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:36: cannot convert nil to type _Ctype_CFDataRef
go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:37: cannot use nil as type _Ctype_CFDataRef in return argument
go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:62: cannot convert nil to type _Ctype_CFDictionaryRef
go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:63: cannot use nil as type _Ctype_CFDictionaryRef in return argument
go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:74: cannot convert &keys[0] (type *_Ctype_CFTypeRef) to type *unsafe.Pointer
go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:74: cannot convert &values[0] (type *_Ctype_CFTypeRef) to type *unsafe.Pointer
go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:87: cannot use nil as type _Ctype_CFStringRef in return argument
go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:90: cannot use nil as type _Ctype_CFStringRef in return argument
go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:141: cannot convert &a[0] (type *_Ctype_CFTypeRef) to type *unsafe.Pointer
go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:141: too many errors
❗ /U/valvarez
(i) go version
go version go1.10 darwin/amd64
```

On investigation it looks like this was filed in https://github.com/keybase/go-keychain/issues/20 and fixed in https://github.com/keybase/go-keychain/pull/23. However,

```
👌 ~/c/other
(i) go get -v -f -u github.com/segmentio/aws-okta
github.com/segmentio/aws-okta (download)
github.com/99designs/keyring (download)
github.com/Sirupsen/logrus (download)
golang.org/x/crypto (download)
golang.org/x/sys (download)
github.com/aws/aws-sdk-go (download)
github.com/mitchellh/go-homedir (download)
github.com/vaughan0/go-ini (download)
golang.org/x/net (download)
github.com/skratchdot/open-golang (download)
github.com/spf13/cobra (download)
github.com/spf13/pflag (download)
github.com/99designs/keyring/vendor/github.com/keybase/go-keychain
# github.com/99designs/keyring/vendor/github.com/keybase/go-keychain
../../go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:29: cannot use nil as type _Ctype_CFDataRef in return argument
../../go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:36: cannot convert nil to type _Ctype_CFDataRef
../../go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:37: cannot use nil as type _Ctype_CFDataRef in return argument
../../go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:62: cannot convert nil to type _Ctype_CFDictionaryRef
../../go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:63: cannot use nil as type _Ctype_CFDictionaryRef in return argument
../../go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:74: cannot convert &keys[0] (type *_Ctype_CFTypeRef) to type *unsafe.Pointer
../../go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:74: cannot convert &values[0] (type *_Ctype_CFTypeRef) to type *unsafe.Pointer
../../go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:87: cannot use nil as type _Ctype_CFStringRef in return argument
../../go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:90: cannot use nil as type _Ctype_CFStringRef in return argument
../../go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:141: cannot convert &a[0] (type *_Ctype_CFTypeRef) to type *unsafe.Pointer
../../go/src/github.com/99designs/keyring/vendor/github.com/keybase/go-keychain/corefoundation.go:141: too many errors
```

still doesn't work; I'm wondering if there's a better way, or at least a documentation update (for how to install this package) is in order; does https://github.com/segmentio/aws-okta/blob/27d69678e14f4598c4bf14cc4a3e2ff1eaa6ed40/vendor/vendor.json#L240 have to change?

**Comment by yangmillstheory** [comment] 2018-03-12 17:07
I can confirm that this works with go 1.9.4

```
👌 ~/c/other
(i) go get -v github.com/segmentio/aws-okta
github.com/aws/aws-sdk-go/aws/awserr
github.com/99designs/keyring/vendor/github.com/dvsekhvalnov/jose2go/keys/ecc
github.com/99designs/keyring/vendor/github.com/dvsekhvalnov/jose2go/base64url
golang.org/x/sys/unix
github.com/99designs/keyring/vendor/golang.org/x/crypto/ssh/terminal
github.com/99designs/keyring/vendor/github.com/keybase/go-keychain
github.com/99designs/keyring/vendor/github.com/mitchellh/go-homedir
github.com/99designs/keyring/vendor/github.com/dvsekhvalnov/jose2go/padding
github.com/99designs/keyring/vendor/github.com/dvsekhvalnov/jose2go/arrays
github.com/99designs/keyring/vendor/github.com/dvsekhvalnov/jose2go/compact
github.com/aws/aws-sdk-go/internal/shareddefaults
github.com/aws/aws-sdk-go/vendor/github.com/go-ini/ini
github.com/aws/aws-sdk-go/aws/endpoints
github.com/aws/aws-sdk-go/aws/client/metadata
github.com/99designs/keyring/vendor/github.com/dvsekhvalnov/jose2go/aes
github.com/99designs/keyring/vendor/github.com/dvsekhvalnov/jose2go/kdf
github.com/aws/aws-sdk-go/vendor/github.com/jmespath/go-jmespath
github.com/aws/aws-sdk-go/internal/sdkrand
github.com/99designs/keyring/vendor/github.com/dvsekhvalnov/jose2go
github.com/mitchellh/go-homedir
github.com/segmentio/aws-okta/lib/saml
github.com/vaughan0/go-ini
golang.org/x/net/html/atom
golang.org/x/net/html
golang.org/x/net/publicsuffix
github.com/skratchdot/open-golang/open
github.com/spf13/pflag
github.com/aws/aws-sdk-go/aws/credentials
github.com/aws/aws-sdk-go/aws/awsutil
golang.org/x/crypto/ssh/terminal
github.com/Sirupsen/logrus
github.com/spf13/cobra
github.com/aws/aws-sdk-go/aws
github.com/aws/aws-sdk-go/aws/request
github.com/aws/aws-sdk-go/aws/client
github.com/aws/aws-sdk-go/aws/corehandlers
github.com/aws/aws-sdk-go/private/protocol
github.com/aws/aws-sdk-go/private/protocol/rest
github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil
github.com/aws/aws-sdk-go/private/protocol/query/queryutil
github.com/aws/aws-sdk-go/aws/credentials/endpointcreds
github.com/aws/aws-sdk-go/aws/ec2metadata
github.com/aws/aws-sdk-go/private/protocol/query
github.com/aws/aws-sdk-go/aws/signer/v4
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds
github.com/aws/aws-sdk-go/aws/defaults
github.com/aws/aws-sdk-go/service/sts
github.com/aws/aws-sdk-go/aws/credentials/stscreds
github.com/aws/aws-sdk-go/aws/session
github.com/99designs/keyring
github.com/segmentio/aws-okta/lib
github.com/segmentio/aws-okta/cmd
github.com/segmentio/aws-okta
👌 ~/c/other
(i) which aws-okta
/Users/valvarez/go/bin/aws-okta
👌 ~/c/other
(i) go version
go version go1.9.4 darwin/amd64
```

**Comment by abraithwaite** [comment] 2018-03-12 17:30
Thanks for the report @yangmillstheory .  We need to update it to be compiled with `CGO_ENABLED=0`.  I believe @dfuentes is working on patches to the keychain libraries to enable this:

https://github.com/dfuentes/go-keychain
https://github.com/dfuentes/keyring/tree/use-keychaintrustapplication-config

I'll let him fill you in on the current status.

**Comment by dfuentes** [comment] 2018-03-12 17:49
The issue is that `99designs/keyring` hasn't yet been updated to use the updated `keybase/go-keychain` which supports go 1.10.  We get around that by vendoring my fork that fixes this incompatibility, but that requires you to pull down dependencies w/ govendor (as opposed to just go get).

As a workaround, you should be able to:
*  `go get` this repo (ignore the build warnings)
* run `make govendor` to download govendor
* run `govendor sync` to pull down vendored deps
* `go build`

I will try to get `99designs/keyring` updated to work with 1.10, then we will be back to `go get` just working.

**Comment by dfuentes** [comment] 2018-03-22 21:17
There is a pr open now in `99designs/keyring` that will fix this when it is merged https://github.com/99designs/keyring/pull/17

**Comment by dfuentes** [comment] 2018-05-08 22:09
I believe this is fixed now that we check in our vendor

**Closed by dfuentes** 2018-05-08 22:09 UTC
Labels: bug
